CREATE DATABASE BDMUSEO;
CREATE TABLE TB_VISITANTES (
    Id_visita INT PRIMARY KEY IDENTITY(1,1),
    Nom_visita NVARCHAR(100) NOT NULL,
    Cant_bol INT NOT NULL,
    hora_ent DATETIME DEFAULT GETDATE() NOT NULL
);
CREATE TABLE TB_VENTAS (
    Id_venta INT PRIMARY KEY IDENTITY(1,1),
    Monto_total DECIMAL(10,2) NOT NULL,
    Metodo_pago NVARCHAR(50) NOT NULL,
    Fecha_venta DATETIME DEFAULT GETDATE() NOT NULL
);

select * from TB_VISITANTES